import "./_globals.scss";

import {Container} from "@mui/material";

import logo from "../../public/logo.png";
import Link from "next/link";

import vk from '../../public/vk.svg';
import telegram from '../../public/telegram.svg';
import whatsapp from '../../public/whatsapp.png';

import './Footer.scss'
import Image from "next/image";


export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <head>

        </head>
        <body>
        {children}

        <footer>
            <Container maxWidth="xl">
                <div className="footer-container">
                    <div className="info">
                        <Link href="/">
                            <Image src={logo} alt="logo" width={250} height={100}/>

                        </Link>


                        <div className="social-media">
                            <p>Наши социальные сети:</p>

                            <ul>
                                <li><a href="#"><Image src={vk} alt="vk"/></a></li>
                                <li><a href="#"><Image src={telegram} alt="telegram"/></a></li>
                                <li><a href="#"><Image src={whatsapp} alt="WhatsApp"/></a></li>
                            </ul>
                        </div>

                        <div className="contacts">
                            <div>
                                <p>г. Мариуполь, ул. Котряевского, 2</p>
                            </div>

                            <div>
                                <p>+7 (949) 000-00-00</p>
                            </div>

                            <div>
                                <p>С 09:00 до 17:00<br/>СБ,ВС – Выходные</p>
                            </div>
                        </div>
                    </div>

                    <nav>
                        <div>
                            <p>Интернет-магазин</p>
                            <ul>
                                <li>Мебельная фурнитура</li>
                                <li>Изделия из стекла</li>
                                <li>Техника и сантехника</li>
                                <li>Раздвижные системы</li>
                                <li>Кромочные материалы</li>
                                <li>Плитные материалы</li>
                            </ul>
                        </div>

                        <div>
                            <p>Компания</p>
                            <ul>
                                <li>Доставка и оплата</li>
                                <li>Сроки выполнения услуг</li>
                                <li>Статус производственного
                                    заказа
                                </li>
                                <li>О компании</li>
                                <li>Контакты</li>
                                <li>Сотрудничество</li>
                            </ul>
                        </div>

                        <div>
                            <p>Партнеры</p>
                            <ul>
                                <li>Hettich</li>
                                <li>Rehau</li>
                                <li>КЕДР</li>
                                <li>EGGER</li>
                                <li>Kronospan</li>
                                <li>Swiss Krono</li>
                                <li>Samet</li>
                                <li>Dollken</li>
                                <li>Hafele</li>
                                <li>KLEIBERIT</li>
                                <li>GranFest</li>
                                <li>Korner</li>
                                <li>Kastamonu</li>
                            </ul>
                        </div>
                    </nav>

                    <div className="map">


                        <div>
                            <iframe
                                src="https://yandex.ru/map-widget/v1/?um=constructor%3Ad618e8cbfcc15e00c78c5cde1ce4b95daa8a59ca30ffce51fc77347308374404&amp;source=constructor"
                                width="320" height="276" frameBorder="0" style={{borderRadius: "50px"}}></iframe>
                        </div>
                    </div>

                    <div className="license">
                        <p>© ООО «Art Mebel», 2024</p>

                        <div className="weber">
                            Сделано с любовью в <a href="http://weber-it.ru">Weber</a>
                        </div>
                    </div>
                </div>


            </Container>
        </footer>
        </body>


        </html>
    );
}
